### ISSUE TITLE
Can I stop consuming gracefully?

### ISSUE THREAD

**Issue by cenkalti** [gmr/rabbitpy#38]
I am using following code to consume messages from a queue:

```python
for message in queue:
    message.pprint(true)
    message.ack()
logger.info("worker has ended")  # cannot drop here
```
Is there a way to stop consuming messages (in another thread or a signal handler)?

What I want to do is to stop consuming messages when my program gets SIGUSR1 signal from OS, finish current task (if there is one), `ACK` last message then exit from program.

**Comment by iotic-labs-vtermanis** [comment]
I have the same problem: How do you stop consuming whilst no messages are being received. The below example hangs on stop_consuming(). I can provide a stack trace of all three threads at the point of deadlock, if that helps.

```python
import rabbitpy
from threading import Thread
from time import sleep


def consumerThread(queue):
    for message in queue:
        if message:
            print('Got msg %s' % message.body)
            #message.ack()
        else:
            print('Empty message')
    print('Finished')


with rabbitpy.Connection('amqp://container:p@localhost:5672/test') as connection:
    with connection.channel() as channel:
        queue = rabbitpy.Queue(channel, 'container_q')

        t = Thread(target = consumerThread, args = (queue,))
        t.start()
        sleep(5)
        print('About to stop')
        queue.stop_consuming()
        print('Joining')
        t.join()
        print('End')
```

**Comment by dasumin** [comment]
+1 to iotic-labs-vtermanis.
stop_consuming() call hangs. Python 2.7

**Comment by dasumin** [comment]
I've made some research about the problem; the following occurs under the hood.

I have two threads: master and rabbitmq consumer.

Consumer thread iterates over the queue iterator; while waiting for a new message, it is waiting for one of the following messages from RabbitMQ: [<class 'pamqp.specification.Deliver'>, <class 'pamqp.specification.CancelOk'>].

Then I call stop() function from the master thread on the consumer thread, and there I call stop_consuming(). In fact, specification.Basic.Cancel is sent from rabbitpy.channel._cancel_consumer, and then it waits to receive specification.Basic.CancelOk as the answer: self._wait_on_frame(specification.Basic.CancelOk).

This answer is immediately received, but is tackled by the consumer thread, which still waits for either Deliver or CancelOk frame.

The ease solution of the problem is not to check CancelOk answer in rabbitpy.channel._cancel_consumer, but I don't know whether it is a correct solution.

Please, share your opinion; I want to use rabbitpy in my project, but currently I'm not able to stop the consumer correctly.

**Comment by gmr** [comment]
Thanks for digging in on this. I'll take a stab at fixing the issue later today.

**Comment by gmr** [comment]
I've implemented a few changes that address this fully and will push it today. I'm going to work through a few more edge cases such as remote cancellation prior to pushing the commit. Expect a 0.26 to drop soon.

**Comment by gmr** [comment]
I believe this is addressed, please reopen if you continue to run into this issue.

**Comment by macfer** [comment]
Surprisingly the problem reappears when queue iterator and some code that affects the queue are executed in separate threads. In the following example one queue receives messages from multiple exchanges and in the meantime it can be bound to new exchanges (and unbound as well).

All works perfectly until you try to stop consuming - the call has no effect. Tested with Python 2.7.8 and rabbitpy 0.26.2.

When you move register_source and unregister_source calls to the run method, stop_consuming works correctly, but this is of course not possible in the real code.

Please, take a look at this. I was looking for alternative solutions (separate thread and queue for each exchange, binding and unbinding queue in the iterator thread) but they are overcomplicated, resource-intensive or unreliable.

```python
from threading import Lock, Thread
from time import sleep
from uuid import uuid1

import rabbitpy

class BusEventsSource(Thread):

    def __init__(self, address):
        super(BusEventsSource, self).__init__()

        self.events = []
        self.sources = []
        self.events_lock = Lock()
        self.sources_lock = Lock()

        self.connection = rabbitpy.Connection(address)
        self.channel = self.connection.channel()
        self.queue = rabbitpy.Queue(self.channel, "framework." + str(uuid1()), exclusive=True,
                                    auto_delete=True)
        self.queue.declare()

    def pop_events(self):
        with self.events_lock:
            event_list = self.events
            self.events = []

        return event_list

    def register_source(self, source):
        with self.sources_lock:
            if source in self.sources:
                raise ValueError("Source already registered.")

            self.sources.append(source)
            exchange = rabbitpy.Exchange(self.channel, source, "fanout", auto_delete=True)
            exchange.declare()
            self.queue.bind(source)

    def unregister_source(self, source):
        with self.sources_lock:
            if source not in self.sources:
                raise ValueError("Source not registered.")

            self.sources.remove(source)
            self.queue.unbind(source)

    def run(self):
        for message in self.queue.consume():
            message.ack()

            with self.events_lock:
                self.events.append((message.exchange, message.body))

        self.connection.close()
        print "exiting run method"


if __name__ == "__main__":
    BES_thread = BusEventsSource("amqp://192.168.0.12:5672/%2F")
    BES_thread.start()
    BES_thread.register_source("framework.test0")
    BES_thread.register_source("framework.test1")
    for _ in range(100):
        sleep(0.1)
        events = BES_thread.pop_events()
        print "number of events: {}".format(len(events))
        for e in events:
            print
            print "source: {}".format(e[0])
            print "content: {}".format(e[1])
            print "----------"
    BES_thread.unregister_source("framework.test0")
    BES_thread.unregister_source("framework.test1")
    sleep(1)
    print "trying to stop consuming"
    BES_thread.queue.stop_consuming()
    sleep(1)
    print "exiting testing code"
```

**Comment by cenkalti** [comment]
@gmr Is there any updates on this issue? What is the recommended way to stop queue iterator from another thread?

**Comment by michael-stefanski** [comment]
@gmr This is still an issue.  What is the recommended, thread-safe way of stop_consuming a Queue if it's in another thread?  thank you

**Comment by dvarelae858** [comment]
the key is maintaining the execution control in the main loop event

**Comment by dvarelae858** [comment]
import signal
import rabbitpy
from threading import Thread, Event
from time import sleep

def signal_handler(sig, frame, stop_event):
    print('Ctrl+C pressed. Stopping consumer thread...')
    stop_event.set()


def consumerThread(queue, stop_event):
    for message in queue:
        if message:
            print('Got msg %s' % message.body)
            message.ack()
        else:
            print('Empty message')
    print('Finished')


# Register signal handler for Ctrl+C
global stop_event
stop_event = Event()  # Event to signal stop

for signame in {'SIGINT', 'SIGTERM'}:
    signal.signal(getattr(signal, signame), lambda signum, frame: signal_handler(signum, frame, stop_event))
#endfor
with rabbitpy.Connection('amqp://admin:admin2023@192.168.18.109/%2F') as connection:
    with connection.channel() as channel:
        queue = rabbitpy.Queue(channel, 'xero.1.invoices.513.n1')

        t = Thread(target = consumerThread, args = (queue,stop_event))
        t.start()
        #sleep(60)
        #print('About to stop')
        #queue.stop_consuming()
        while not stop_event.is_set():
            None
        #endwhile
        print('About to stop')
        queue.stop_consuming()
        print('Joining')
        t.join()
        print('End')
